using System.Collections.Generic;
using System.Linq;

namespace NipSharp
{
    public static class NipAliases
    {
        public static readonly Dictionary<string, int> Type = new();
        public static readonly Dictionary<string, int> ClassId = new();
        public static readonly Dictionary<string, int> Class = new();
        public static readonly Dictionary<string, int> Quality = new();
        public static readonly Dictionary<string, int> Flag = new();
        public static readonly Dictionary<string, int> Color = new();
        public static readonly Dictionary<string, (int, int?)> Stat = new();
        public static readonly HashSet<string> KnownProperties = new();
        public static readonly ILookup<(int, int?), string> InverseStat;

        static NipAliases()
        {
            #region KnownProperties

            KnownProperties.Add("type");
            KnownProperties.Add("name");
            KnownProperties.Add("color");
            KnownProperties.Add("class");
            KnownProperties.Add("quality");
            KnownProperties.Add("flag");
            KnownProperties.Add("level");
            KnownProperties.Add("prefix");
            KnownProperties.Add("suffix");

            #endregion

            #region AliasType

            Type["shield"] = 2;
            Type["armor"] = 3;
            Type["gold"] = 4;
            Type["bowquiver"] = 5;
            Type["crossbowquiver"] = 6;
            Type["playerbodypart"] = 7;
            Type["herb"] = 8;
            Type["potion"] = 9;
            Type["ring"] = 10;
            Type["elixir"] = 11;
            Type["amulet"] = 12;
            Type["charm"] = 13;
            Type["notused"] = 14;
            Type["boots"] = 15;
            Type["gloves"] = 16;
            Type["notused"] = 17;
            Type["book"] = 18;
            Type["belt"] = 19;
            Type["gem"] = 20;
            Type["torch"] = 21;
            Type["scroll"] = 22;
            Type["notused"] = 23;
            Type["scepter"] = 24;
            Type["wand"] = 25;
            Type["staff"] = 26;
            Type["bow"] = 27;
            Type["axe"] = 28;
            Type["club"] = 29;
            Type["sword"] = 30;
            Type["hammer"] = 31;
            Type["knife"] = 32;
            Type["spear"] = 33;
            Type["polearm"] = 34;
            Type["crossbow"] = 35;
            Type["mace"] = 36;
            Type["helm"] = 37;
            Type["missilepotion"] = 38;
            Type["quest"] = 39;
            Type["bodypart"] = 40;
            Type["key"] = 41;
            Type["throwingknife"] = 42;
            Type["throwingaxe"] = 43;
            Type["javelin"] = 44;
            Type["weapon"] = 45;
            Type["meleeweapon"] = 46;
            Type["missileweapon"] = 47;
            Type["thrownweapon"] = 48;
            Type["comboweapon"] = 49;
            Type["anyarmor"] = 50;
            Type["anyshield"] = 51;
            Type["miscellaneous"] = 52;
            Type["socketfiller"] = 53;
            Type["secondhand"] = 54;
            Type["stavesandrods"] = 55;
            Type["missile"] = 56;
            Type["blunt"] = 57;
            Type["jewel"] = 58;
            Type["classspecific"] = 59;
            Type["amazonitem"] = 60;
            Type["barbarianitem"] = 61;
            Type["necromanceritem"] = 62;
            Type["paladinitem"] = 63;
            Type["sorceressitem"] = 64;
            Type["assassinitem"] = 65;
            Type["druiditem"] = 66;
            Type["handtohand"] = 67;
            Type["orb"] = 68;
            Type["voodooheads"] = 69;
            Type["auricshields"] = 70;
            Type["primalhelm"] = 71;
            Type["pelt"] = 72;
            Type["cloak"] = 73;
            Type["rune"] = 74;
            Type["circlet"] = 75;
            Type["healingpotion"] = 76;
            Type["manapotion"] = 77;
            Type["rejuvpotion"] = 78;
            Type["staminapotion"] = 79;
            Type["antidotepotion"] = 80;
            Type["thawingpotion"] = 81;
            Type["smallcharm"] = 82;
            Type["mediumcharm"] = 83;
            Type["largecharm"] = 84;
            Type["amazonbow"] = 85;
            Type["amazonspear"] = 86;
            Type["amazonjavelin"] = 87;
            Type["assassinclaw"] = 88;
            Type["magicbowquiv"] = 89;
            Type["magicxbowquiv"] = 90;
            Type["chippedgem"] = 91;
            Type["flawedgem"] = 92;
            Type["standardgem"] = 93;
            Type["flawlessgem"] = 94;
            Type["perfectgem"] = 95;
            Type["amethyst"] = 96;
            Type["diamond"] = 97;
            Type["emerald"] = 98;
            Type["ruby"] = 99;
            Type["sapphire"] = 100;
            Type["topaz"] = 101;
            Type["skull"] = 102;

            #endregion

            #region AliasClassId

            ClassId["hax"] = ClassId["handaxe"] = 0;
            ClassId["axe"] = 1;
            ClassId["2ax"] = ClassId["doubleaxe"] = 2;
            ClassId["mpi"] = ClassId["militarypick"] = 3;
            ClassId["wax"] = ClassId["waraxe"] = 4;
            ClassId["lax"] = ClassId["largeaxe"] = 5;
            ClassId["bax"] = ClassId["broadaxe"] = 6;
            ClassId["btx"] = ClassId["battleaxe"] = 7;
            ClassId["gax"] = ClassId["greataxe"] = 8;
            ClassId["gix"] = ClassId["giantaxe"] = 9;
            ClassId["wnd"] = ClassId["wand"] = 10;
            ClassId["ywn"] = ClassId["yewwand"] = 11;
            ClassId["bwn"] = ClassId["bonewand"] = 12;
            ClassId["gwn"] = ClassId["grimwand"] = 13;
            ClassId["clb"] = ClassId["club"] = 14;
            ClassId["scp"] = ClassId["scepter"] = 15;
            ClassId["gsc"] = ClassId["grandscepter"] = 16;
            ClassId["wsp"] = ClassId["warscepter"] = 17;
            ClassId["spc"] = ClassId["spikedclub"] = 18;
            ClassId["mac"] = ClassId["mace"] = 19;
            ClassId["mst"] = ClassId["morningstar"] = 20;
            ClassId["fla"] = ClassId["flail"] = 21;
            ClassId["whm"] = ClassId["warhammer"] = 22;
            ClassId["mau"] = ClassId["maul"] = 23;
            ClassId["gma"] = ClassId["greatmaul"] = 24;
            ClassId["ssd"] = ClassId["shortsword"] = 25;
            ClassId["scm"] = ClassId["scimitar"] = 26;
            ClassId["sbr"] = ClassId["sabre"] = 27;
            ClassId["flc"] = ClassId["falchion"] = 28;
            ClassId["crs"] = ClassId["crystalsword"] = 29;
            ClassId["bsd"] = ClassId["broadsword"] = 30;
            ClassId["lsd"] = ClassId["longsword"] = 31;
            ClassId["wsd"] = ClassId["warsword"] = 32;
            ClassId["2hs"] = ClassId["twohandedsword"] = 33;
            ClassId["clm"] = ClassId["claymore"] = 34;
            ClassId["gis"] = ClassId["giantsword"] = 35;
            ClassId["bsw"] = ClassId["bastardsword"] = 36;
            ClassId["flb"] = ClassId["flamberge"] = 37;
            ClassId["gsd"] = ClassId["greatsword"] = 38;
            ClassId["dgr"] = ClassId["dagger"] = 39;
            ClassId["dir"] = ClassId["dirk"] = 40;
            ClassId["kri"] = ClassId["kris"] = 41;
            ClassId["bld"] = ClassId["blade"] = 42;
            ClassId["tkf"] = ClassId["throwingknife"] = 43;
            ClassId["tax"] = ClassId["throwingaxe"] = 44;
            ClassId["bkf"] = ClassId["balancedknife"] = 45;
            ClassId["bal"] = ClassId["balancedaxe"] = 46;
            ClassId["jav"] = ClassId["javelin"] = 47;
            ClassId["pil"] = ClassId["pilum"] = 48;
            ClassId["ssp"] = ClassId["shortspear"] = 49;
            ClassId["glv"] = ClassId["glaive"] = 50;
            ClassId["tsp"] = ClassId["throwingspear"] = 51;
            ClassId["spr"] = ClassId["spear"] = 52;
            ClassId["tri"] = ClassId["trident"] = 53;
            ClassId["brn"] = ClassId["brandistock"] = 54;
            ClassId["spt"] = ClassId["spetum"] = 55;
            ClassId["pik"] = ClassId["pike"] = 56;
            ClassId["bar"] = ClassId["bardiche"] = 57;
            ClassId["vou"] = ClassId["voulge"] = 58;
            ClassId["scy"] = ClassId["scythe"] = 59;
            ClassId["pax"] = ClassId["poleaxe"] = 60;
            ClassId["hal"] = ClassId["halberd"] = 61;
            ClassId["wsc"] = ClassId["warscythe"] = 62;
            ClassId["sst"] = ClassId["shortstaff"] = 63;
            ClassId["lst"] = ClassId["longstaff"] = 64;
            ClassId["cst"] = ClassId["gnarledstaff"] = 65;
            ClassId["bst"] = ClassId["battlestaff"] = 66;
            ClassId["wst"] = ClassId["warstaff"] = 67;
            ClassId["sbw"] = ClassId["shortbow"] = 68;
            ClassId["hbw"] = ClassId["hunter'sbow"] = 69;
            ClassId["lbw"] = ClassId["longbow"] = 70;
            ClassId["cbw"] = ClassId["compositebow"] = 71;
            ClassId["sbb"] = ClassId["shortbattlebow"] = 72;
            ClassId["lbb"] = ClassId["longbattlebow"] = 73;
            ClassId["swb"] = ClassId["shortwarbow"] = 74;
            ClassId["lwb"] = ClassId["longwarbow"] = 75;
            ClassId["lxb"] = ClassId["lightcrossbow"] = 76;
            ClassId["mxb"] = ClassId["crossbow"] = 77;
            ClassId["hxb"] = ClassId["heavycrossbow"] = 78;
            ClassId["rxb"] = ClassId["repeatingcrossbow"] = 79;
            ClassId["gps"] = ClassId["rancidgaspotion"] = 80;
            ClassId["ops"] = ClassId["oilpotion"] = 81;
            ClassId["gpm"] = ClassId["chokinggaspotion"] = 82;
            ClassId["opm"] = ClassId["explodingpotion"] = 83;
            ClassId["gpl"] = ClassId["stranglinggaspotion"] = 84;
            ClassId["opl"] = ClassId["fulminatingpotion"] = 85;
            ClassId["d33"] = ClassId["decoygidbinn"] = 86;
            ClassId["g33"] = ClassId["thegidbinn"] = 87;
            ClassId["leg"] = ClassId["wirt'sleg"] = 88;
            ClassId["hdm"] = ClassId["horadricmalus"] = 89;
            ClassId["hfh"] = ClassId["hellforgehammer"] = 90;
            ClassId["hst"] = ClassId["horadricstaff"] = 91;
            ClassId["msf"] = ClassId["shaftofthehoradricstaff"] = 92;
            ClassId["9ha"] = ClassId["hatchet"] = 93;
            ClassId["9ax"] = ClassId["cleaver"] = 94;
            ClassId["92a"] = ClassId["twinaxe"] = 95;
            ClassId["9mp"] = ClassId["crowbill"] = 96;
            ClassId["9wa"] = ClassId["naga"] = 97;
            ClassId["9la"] = ClassId["militaryaxe"] = 98;
            ClassId["9ba"] = ClassId["beardedaxe"] = 99;
            ClassId["9bt"] = ClassId["tabar"] = 100;
            ClassId["9ga"] = ClassId["gothicaxe"] = 101;
            ClassId["9gi"] = ClassId["ancientaxe"] = 102;
            ClassId["9wn"] = ClassId["burntwand"] = 103;
            ClassId["9yw"] = ClassId["petrifiedwand"] = 104;
            ClassId["9bw"] = ClassId["tombwand"] = 105;
            ClassId["9gw"] = ClassId["gravewand"] = 106;
            ClassId["9cl"] = ClassId["cudgel"] = 107;
            ClassId["9sc"] = ClassId["runescepter"] = 108;
            ClassId["9qs"] = ClassId["holywatersprinkler"] = 109;
            ClassId["9ws"] = ClassId["divinescepter"] = 110;
            ClassId["9sp"] = ClassId["barbedclub"] = 111;
            ClassId["9ma"] = ClassId["flangedmace"] = 112;
            ClassId["9mt"] = ClassId["jaggedstar"] = 113;
            ClassId["9fl"] = ClassId["knout"] = 114;
            ClassId["9wh"] = ClassId["battlehammer"] = 115;
            ClassId["9m9"] = ClassId["warclub"] = 116;
            ClassId["9gm"] = ClassId["marteldefer"] = 117;
            ClassId["9ss"] = ClassId["gladius"] = 118;
            ClassId["9sm"] = ClassId["cutlass"] = 119;
            ClassId["9sb"] = ClassId["shamshir"] = 120;
            ClassId["9fc"] = ClassId["tulwar"] = 121;
            ClassId["9cr"] = ClassId["dimensionalblade"] = 122;
            ClassId["9bs"] = ClassId["battlesword"] = 123;
            ClassId["9ls"] = ClassId["runesword"] = 124;
            ClassId["9wd"] = ClassId["ancientsword"] = 125;
            ClassId["92h"] = ClassId["espandon"] = 126;
            ClassId["9cm"] = ClassId["dacianfalx"] = 127;
            ClassId["9gs"] = ClassId["tusksword"] = 128;
            ClassId["9b9"] = ClassId["gothicsword"] = 129;
            ClassId["9fb"] = ClassId["zweihander"] = 130;
            ClassId["9gd"] = ClassId["executionersword"] = 131;
            ClassId["9dg"] = ClassId["poignard"] = 132;
            ClassId["9di"] = ClassId["rondel"] = 133;
            ClassId["9kr"] = ClassId["cinquedeas"] = 134;
            ClassId["9bl"] = ClassId["stiletto"] = 135;
            ClassId["9tk"] = ClassId["battledart"] = 136;
            ClassId["9ta"] = ClassId["francisca"] = 137;
            ClassId["9bk"] = ClassId["wardart"] = 138;
            ClassId["9b8"] = ClassId["hurlbat"] = 139;
            ClassId["9ja"] = ClassId["warjavelin"] = 140;
            ClassId["9pi"] = ClassId["greatpilum"] = 141;
            ClassId["9s9"] = ClassId["simbilan"] = 142;
            ClassId["9gl"] = ClassId["spiculum"] = 143;
            ClassId["9ts"] = ClassId["harpoon"] = 144;
            ClassId["9sr"] = ClassId["warspear"] = 145;
            ClassId["9tr"] = ClassId["fuscina"] = 146;
            ClassId["9br"] = ClassId["warfork"] = 147;
            ClassId["9st"] = ClassId["yari"] = 148;
            ClassId["9p9"] = ClassId["lance"] = 149;
            ClassId["9b7"] = ClassId["lochaberaxe"] = 150;
            ClassId["9vo"] = ClassId["bill"] = 151;
            ClassId["9s8"] = ClassId["battlescythe"] = 152;
            ClassId["9pa"] = ClassId["partizan"] = 153;
            ClassId["9h9"] = ClassId["becdecorbin"] = 154;
            ClassId["9wc"] = ClassId["grimscythe"] = 155;
            ClassId["8ss"] = ClassId["jostaff"] = 156;
            ClassId["8ls"] = ClassId["quarterstaff"] = 157;
            ClassId["8cs"] = ClassId["cedarstaff"] = 158;
            ClassId["8bs"] = ClassId["gothicstaff"] = 159;
            ClassId["8ws"] = ClassId["runestaff"] = 160;
            ClassId["8sb"] = ClassId["edgebow"] = 161;
            ClassId["8hb"] = ClassId["razorbow"] = 162;
            ClassId["8lb"] = ClassId["cedarbow"] = 163;
            ClassId["8cb"] = ClassId["doublebow"] = 164;
            ClassId["8s8"] = ClassId["shortsiegebow"] = 165;
            ClassId["8l8"] = ClassId["largesiegebow"] = 166;
            ClassId["8sw"] = ClassId["runebow"] = 167;
            ClassId["8lw"] = ClassId["gothicbow"] = 168;
            ClassId["8lx"] = ClassId["arbalest"] = 169;
            ClassId["8mx"] = ClassId["siegecrossbow"] = 170;
            ClassId["8hx"] = ClassId["ballista"] = 171;
            ClassId["8rx"] = ClassId["chukonu"] = 172;
            ClassId["qf1"] = ClassId["khalim'sflail"] = 173;
            ClassId["qf2"] = ClassId["khalim'swill"] = 174;
            ClassId["ktr"] = ClassId["katar"] = 175;
            ClassId["wrb"] = ClassId["wristblade"] = 176;
            ClassId["axf"] = ClassId["hatchethands"] = 177;
            ClassId["ces"] = ClassId["cestus"] = 178;
            ClassId["clw"] = ClassId["claws"] = 179;
            ClassId["btl"] = ClassId["bladetalons"] = 180;
            ClassId["skr"] = ClassId["scissorskatar"] = 181;
            ClassId["9ar"] = ClassId["quhab"] = 182;
            ClassId["9wb"] = ClassId["wristspike"] = 183;
            ClassId["9xf"] = ClassId["fascia"] = 184;
            ClassId["9cs"] = ClassId["handscythe"] = 185;
            ClassId["9lw"] = ClassId["greaterclaws"] = 186;
            ClassId["9tw"] = ClassId["greatertalons"] = 187;
            ClassId["9qr"] = ClassId["scissorsquhab"] = 188;
            ClassId["7ar"] = ClassId["suwayyah"] = 189;
            ClassId["7wb"] = ClassId["wristsword"] = 190;
            ClassId["7xf"] = ClassId["warfist"] = 191;
            ClassId["7cs"] = ClassId["battlecestus"] = 192;
            ClassId["7lw"] = ClassId["feralclaws"] = 193;
            ClassId["7tw"] = ClassId["runictalons"] = 194;
            ClassId["7qr"] = ClassId["scissorssuwayyah"] = 195;
            ClassId["7ha"] = ClassId["tomahawk"] = 196;
            ClassId["7ax"] = ClassId["smallcrescent"] = 197;
            ClassId["72a"] = ClassId["ettinaxe"] = 198;
            ClassId["7mp"] = ClassId["warspike"] = 199;
            ClassId["7wa"] = ClassId["berserkeraxe"] = 200;
            ClassId["7la"] = ClassId["feralaxe"] = 201;
            ClassId["7ba"] = ClassId["silveredgedaxe"] = 202;
            ClassId["7bt"] = ClassId["decapitator"] = 203;
            ClassId["7ga"] = ClassId["championaxe"] = 204;
            ClassId["7gi"] = ClassId["gloriousaxe"] = 205;
            ClassId["7wn"] = ClassId["polishedwand"] = 206;
            ClassId["7yw"] = ClassId["ghostwand"] = 207;
            ClassId["7bw"] = ClassId["lichwand"] = 208;
            ClassId["7gw"] = ClassId["unearthedwand"] = 209;
            ClassId["7cl"] = ClassId["truncheon"] = 210;
            ClassId["7sc"] = ClassId["mightyscepter"] = 211;
            ClassId["7qs"] = ClassId["seraphrod"] = 212;
            ClassId["7ws"] = ClassId["caduceus"] = 213;
            ClassId["7sp"] = ClassId["tyrantclub"] = 214;
            ClassId["7ma"] = ClassId["reinforcedmace"] = 215;
            ClassId["7mt"] = ClassId["devilstar"] = 216;
            ClassId["7fl"] = ClassId["scourge"] = 217;
            ClassId["7wh"] = ClassId["legendarymallet"] = 218;
            ClassId["7m7"] = ClassId["ogremaul"] = 219;
            ClassId["7gm"] = ClassId["thundermaul"] = 220;
            ClassId["7ss"] = ClassId["falcata"] = 221;
            ClassId["7sm"] = ClassId["ataghan"] = 222;
            ClassId["7sb"] = ClassId["elegantblade"] = 223;
            ClassId["7fc"] = ClassId["hydraedge"] = 224;
            ClassId["7cr"] = ClassId["phaseblade"] = 225;
            ClassId["7bs"] = ClassId["conquestsword"] = 226;
            ClassId["7ls"] = ClassId["crypticsword"] = 227;
            ClassId["7wd"] = ClassId["mythicalsword"] = 228;
            ClassId["72h"] = ClassId["legendsword"] = 229;
            ClassId["7cm"] = ClassId["highlandblade"] = 230;
            ClassId["7gs"] = ClassId["balrogblade"] = 231;
            ClassId["7b7"] = ClassId["championsword"] = 232;
            ClassId["7fb"] = ClassId["colossussword"] = 233;
            ClassId["7gd"] = ClassId["colossusblade"] = 234;
            ClassId["7dg"] = ClassId["boneknife"] = 235;
            ClassId["7di"] = ClassId["mithrilpoint"] = 236;
            ClassId["7kr"] = ClassId["fangedknife"] = 237;
            ClassId["7bl"] = ClassId["legendspike"] = 238;
            ClassId["7tk"] = ClassId["flyingknife"] = 239;
            ClassId["7ta"] = ClassId["flyingaxe"] = 240;
            ClassId["7bk"] = ClassId["wingedknife"] = 241;
            ClassId["7b8"] = ClassId["wingedaxe"] = 242;
            ClassId["7ja"] = ClassId["hyperionjavelin"] = 243;
            ClassId["7pi"] = ClassId["stygianpilum"] = 244;
            ClassId["7s7"] = ClassId["balrogspear"] = 245;
            ClassId["7gl"] = ClassId["ghostglaive"] = 246;
            ClassId["7ts"] = ClassId["wingedharpoon"] = 247;
            ClassId["7sr"] = ClassId["hyperionspear"] = 248;
            ClassId["7tr"] = ClassId["stygianpike"] = 249;
            ClassId["7br"] = ClassId["mancatcher"] = 250;
            ClassId["7st"] = ClassId["ghostspear"] = 251;
            ClassId["7p7"] = ClassId["warpike"] = 252;
            ClassId["7o7"] = ClassId["ogreaxe"] = 253;
            ClassId["7vo"] = ClassId["colossusvoulge"] = 254;
            ClassId["7s8"] = ClassId["thresher"] = 255;
            ClassId["7pa"] = ClassId["crypticaxe"] = 256;
            ClassId["7h7"] = ClassId["greatpoleaxe"] = 257;
            ClassId["7wc"] = ClassId["giantthresher"] = 258;
            ClassId["6ss"] = ClassId["walkingstick"] = 259;
            ClassId["6ls"] = ClassId["stalagmite"] = 260;
            ClassId["6cs"] = ClassId["elderstaff"] = 261;
            ClassId["6bs"] = ClassId["shillelagh"] = 262;
            ClassId["6ws"] = ClassId["archonstaff"] = 263;
            ClassId["6sb"] = ClassId["spiderbow"] = 264;
            ClassId["6hb"] = ClassId["bladebow"] = 265;
            ClassId["6lb"] = ClassId["shadowbow"] = 266;
            ClassId["6cb"] = ClassId["greatbow"] = 267;
            ClassId["6s7"] = ClassId["diamondbow"] = 268;
            ClassId["6l7"] = ClassId["crusaderbow"] = 269;
            ClassId["6sw"] = ClassId["wardbow"] = 270;
            ClassId["6lw"] = ClassId["hydrabow"] = 271;
            ClassId["6lx"] = ClassId["pelletbow"] = 272;
            ClassId["6mx"] = ClassId["gorgoncrossbow"] = 273;
            ClassId["6hx"] = ClassId["colossuscrossbow"] = 274;
            ClassId["6rx"] = ClassId["demoncrossbow"] = 275;
            ClassId["ob1"] = ClassId["eagleorb"] = 276;
            ClassId["ob2"] = ClassId["sacredglobe"] = 277;
            ClassId["ob3"] = ClassId["smokedsphere"] = 278;
            ClassId["ob4"] = ClassId["claspedorb"] = 279;
            ClassId["ob5"] = ClassId["jared'sstone"] = 280;
            ClassId["am1"] = ClassId["stagbow"] = 281;
            ClassId["am2"] = ClassId["reflexbow"] = 282;
            ClassId["am3"] = ClassId["maidenspear"] = 283;
            ClassId["am4"] = ClassId["maidenpike"] = 284;
            ClassId["am5"] = ClassId["maidenjavelin"] = 285;
            ClassId["ob6"] = ClassId["glowingorb"] = 286;
            ClassId["ob7"] = ClassId["crystallineglobe"] = 287;
            ClassId["ob8"] = ClassId["cloudysphere"] = 288;
            ClassId["ob9"] = ClassId["sparklingball"] = 289;
            ClassId["oba"] = ClassId["swirlingcrystal"] = 290;
            ClassId["am6"] = ClassId["ashwoodbow"] = 291;
            ClassId["am7"] = ClassId["ceremonialbow"] = 292;
            ClassId["am8"] = ClassId["ceremonialspear"] = 293;
            ClassId["am9"] = ClassId["ceremonialpike"] = 294;
            ClassId["ama"] = ClassId["ceremonialjavelin"] = 295;
            ClassId["obb"] = ClassId["heavenlystone"] = 296;
            ClassId["obc"] = ClassId["eldritchorb"] = 297;
            ClassId["obd"] = ClassId["demonheart"] = 298;
            ClassId["obe"] = ClassId["vortexorb"] = 299;
            ClassId["obf"] = ClassId["dimensionalshard"] = 300;
            ClassId["amb"] = ClassId["matriarchalbow"] = 301;
            ClassId["amc"] = ClassId["grandmatronbow"] = 302;
            ClassId["amd"] = ClassId["matriarchalspear"] = 303;
            ClassId["ame"] = ClassId["matriarchalpike"] = 304;
            ClassId["amf"] = ClassId["matriarchaljavelin"] = 305;
            ClassId["cap"] = 306;
            ClassId["skp"] = ClassId["skullcap"] = 307;
            ClassId["hlm"] = ClassId["helm"] = 308;
            ClassId["fhl"] = ClassId["fullhelm"] = 309;
            ClassId["ghm"] = ClassId["greathelm"] = 310;
            ClassId["crn"] = ClassId["crown"] = 311;
            ClassId["msk"] = ClassId["mask"] = 312;
            ClassId["qui"] = ClassId["quiltedarmor"] = 313;
            ClassId["lea"] = ClassId["leatherarmor"] = 314;
            ClassId["hla"] = ClassId["hardleatherarmor"] = 315;
            ClassId["stu"] = ClassId["studdedleather"] = 316;
            ClassId["rng"] = ClassId["ringmail"] = 317;
            ClassId["scl"] = ClassId["scalemail"] = 318;
            ClassId["chn"] = ClassId["chainmail"] = 319;
            ClassId["brs"] = ClassId["breastplate"] = 320;
            ClassId["spl"] = ClassId["splintmail"] = 321;
            ClassId["plt"] = ClassId["platemail"] = 322;
            ClassId["fld"] = ClassId["fieldplate"] = 323;
            ClassId["gth"] = ClassId["gothicplate"] = 324;
            ClassId["ful"] = ClassId["fullplatemail"] = 325;
            ClassId["aar"] = ClassId["ancientarmor"] = 326;
            ClassId["ltp"] = ClassId["lightplate"] = 327;
            ClassId["buc"] = ClassId["buckler"] = 328;
            ClassId["sml"] = ClassId["smallshield"] = 329;
            ClassId["lrg"] = ClassId["largeshield"] = 330;
            ClassId["kit"] = ClassId["kiteshield"] = 331;
            ClassId["tow"] = ClassId["towershield"] = 332;
            ClassId["gts"] = ClassId["gothicshield"] = 333;
            ClassId["lgl"] = ClassId["leathergloves"] = 334;
            ClassId["vgl"] = ClassId["heavygloves"] = 335;
            ClassId["mgl"] = ClassId["chaingloves"] = 336;
            ClassId["tgl"] = ClassId["lightgauntlets"] = 337;
            ClassId["hgl"] = ClassId["gauntlets"] = 338;
            ClassId["lbt"] = ClassId["boots"] = 339;
            ClassId["vbt"] = ClassId["heavyboots"] = 340;
            ClassId["mbt"] = ClassId["chainboots"] = 341;
            ClassId["tbt"] = ClassId["lightplatedboots"] = 342;
            ClassId["hbt"] = ClassId["greaves"] = 343;
            ClassId["lbl"] = ClassId["sash"] = 344;
            ClassId["vbl"] = ClassId["lightbelt"] = 345;
            ClassId["mbl"] = ClassId["belt"] = 346;
            ClassId["tbl"] = ClassId["heavybelt"] = 347;
            ClassId["hbl"] = ClassId["platedbelt"] = 348;
            ClassId["bhm"] = ClassId["bonehelm"] = 349;
            ClassId["bsh"] = ClassId["boneshield"] = 350;
            ClassId["spk"] = ClassId["spikedshield"] = 351;
            ClassId["xap"] = ClassId["warhat"] = 352;
            ClassId["xkp"] = ClassId["sallet"] = 353;
            ClassId["xlm"] = ClassId["casque"] = 354;
            ClassId["xhl"] = ClassId["basinet"] = 355;
            ClassId["xhm"] = ClassId["wingedhelm"] = 356;
            ClassId["xrn"] = ClassId["grandcrown"] = 357;
            ClassId["xsk"] = ClassId["deathmask"] = 358;
            ClassId["xui"] = ClassId["ghostarmor"] = 359;
            ClassId["xea"] = ClassId["serpentskinarmor"] = 360;
            ClassId["xla"] = ClassId["demonhidearmor"] = 361;
            ClassId["xtu"] = ClassId["trellisedarmor"] = 362;
            ClassId["xng"] = ClassId["linkedmail"] = 363;
            ClassId["xcl"] = ClassId["tigulatedmail"] = 364;
            ClassId["xhn"] = ClassId["mesharmor"] = 365;
            ClassId["xrs"] = ClassId["cuirass"] = 366;
            ClassId["xpl"] = ClassId["russetarmor"] = 367;
            ClassId["xlt"] = ClassId["templarcoat"] = 368;
            ClassId["xld"] = ClassId["sharktootharmor"] = 369;
            ClassId["xth"] = ClassId["embossedplate"] = 370;
            ClassId["xul"] = ClassId["chaosarmor"] = 371;
            ClassId["xar"] = ClassId["ornateplate"] = 372;
            ClassId["xtp"] = ClassId["mageplate"] = 373;
            ClassId["xuc"] = ClassId["defender"] = 374;
            ClassId["xml"] = ClassId["roundshield"] = 375;
            ClassId["xrg"] = ClassId["scutum"] = 376;
            ClassId["xit"] = ClassId["dragonshield"] = 377;
            ClassId["xow"] = ClassId["pavise"] = 378;
            ClassId["xts"] = ClassId["ancientshield"] = 379;
            ClassId["xlg"] = ClassId["demonhidegloves"] = 380;
            ClassId["xvg"] = ClassId["sharkskingloves"] = 381;
            ClassId["xmg"] = ClassId["heavybracers"] = 382;
            ClassId["xtg"] = ClassId["battlegauntlets"] = 383;
            ClassId["xhg"] = ClassId["wargauntlets"] = 384;
            ClassId["xlb"] = ClassId["demonhideboots"] = 385;
            ClassId["xvb"] = ClassId["sharkskinboots"] = 386;
            ClassId["xmb"] = ClassId["meshboots"] = 387;
            ClassId["xtb"] = ClassId["battleboots"] = 388;
            ClassId["xhb"] = ClassId["warboots"] = 389;
            ClassId["zlb"] = ClassId["demonhidesash"] = 390;
            ClassId["zvb"] = ClassId["sharkskinbelt"] = 391;
            ClassId["zmb"] = ClassId["meshbelt"] = 392;
            ClassId["ztb"] = ClassId["battlebelt"] = 393;
            ClassId["zhb"] = ClassId["warbelt"] = 394;
            ClassId["xh9"] = ClassId["grimhelm"] = 395;
            ClassId["xsh"] = ClassId["grimshield"] = 396;
            ClassId["xpk"] = ClassId["barbedshield"] = 397;
            ClassId["dr1"] = ClassId["wolfhead"] = 398;
            ClassId["dr2"] = ClassId["hawkhelm"] = 399;
            ClassId["dr3"] = ClassId["antlers"] = 400;
            ClassId["dr4"] = ClassId["falconmask"] = 401;
            ClassId["dr5"] = ClassId["spiritmask"] = 402;
            ClassId["ba1"] = ClassId["jawbonecap"] = 403;
            ClassId["ba2"] = ClassId["fangedhelm"] = 404;
            ClassId["ba3"] = ClassId["hornedhelm"] = 405;
            ClassId["ba4"] = ClassId["assaulthelmet"] = 406;
            ClassId["ba5"] = ClassId["avengerguard"] = 407;
            ClassId["pa1"] = ClassId["targe"] = 408;
            ClassId["pa2"] = ClassId["rondache"] = 409;
            ClassId["pa3"] = ClassId["heraldicshield"] = 410;
            ClassId["pa4"] = ClassId["aerinshield"] = 411;
            ClassId["pa5"] = ClassId["crownshield"] = 412;
            ClassId["ne1"] = ClassId["preservedhead"] = 413;
            ClassId["ne2"] = ClassId["zombiehead"] = 414;
            ClassId["ne3"] = ClassId["unravellerhead"] = 415;
            ClassId["ne4"] = ClassId["gargoylehead"] = 416;
            ClassId["ne5"] = ClassId["demonhead"] = 417;
            ClassId["ci0"] = ClassId["circlet"] = 418;
            ClassId["ci1"] = ClassId["coronet"] = 419;
            ClassId["ci2"] = ClassId["tiara"] = 420;
            ClassId["ci3"] = ClassId["diadem"] = 421;
            ClassId["uap"] = ClassId["shako"] = 422;
            ClassId["ukp"] = ClassId["hydraskull"] = 423;
            ClassId["ulm"] = ClassId["armet"] = 424;
            ClassId["uhl"] = ClassId["giantconch"] = 425;
            ClassId["uhm"] = ClassId["spiredhelm"] = 426;
            ClassId["urn"] = ClassId["corona"] = 427;
            ClassId["usk"] = ClassId["demonhead"] = 428;
            ClassId["uui"] = ClassId["duskshroud"] = 429;
            ClassId["uea"] = ClassId["wyrmhide"] = 430;
            ClassId["ula"] = ClassId["scarabhusk"] = 431;
            ClassId["utu"] = ClassId["wirefleece"] = 432;
            ClassId["ung"] = ClassId["diamondmail"] = 433;
            ClassId["ucl"] = ClassId["loricatedmail"] = 434;
            ClassId["uhn"] = ClassId["boneweave"] = 435;
            ClassId["urs"] = ClassId["greathauberk"] = 436;
            ClassId["upl"] = ClassId["balrogskin"] = 437;
            ClassId["ult"] = ClassId["hellforgeplate"] = 438;
            ClassId["uld"] = ClassId["krakenshell"] = 439;
            ClassId["uth"] = ClassId["lacqueredplate"] = 440;
            ClassId["uul"] = ClassId["shadowplate"] = 441;
            ClassId["uar"] = ClassId["sacredarmor"] = 442;
            ClassId["utp"] = ClassId["archonplate"] = 443;
            ClassId["uuc"] = ClassId["heater"] = 444;
            ClassId["uml"] = ClassId["luna"] = 445;
            ClassId["urg"] = ClassId["hyperion"] = 446;
            ClassId["uit"] = ClassId["monarch"] = 447;
            ClassId["uow"] = ClassId["aegis"] = 448;
            ClassId["uts"] = ClassId["ward"] = 449;
            ClassId["ulg"] = ClassId["bramblemitts"] = 450;
            ClassId["uvg"] = ClassId["vampirebonegloves"] = 451;
            ClassId["umg"] = ClassId["vambraces"] = 452;
            ClassId["utg"] = ClassId["crusadergauntlets"] = 453;
            ClassId["uhg"] = ClassId["ogregauntlets"] = 454;
            ClassId["ulb"] = ClassId["wyrmhideboots"] = 455;
            ClassId["uvb"] = ClassId["scarabshellboots"] = 456;
            ClassId["umb"] = ClassId["boneweaveboots"] = 457;
            ClassId["utb"] = ClassId["mirroredboots"] = 458;
            ClassId["uhb"] = ClassId["myrmidongreaves"] = 459;
            ClassId["ulc"] = ClassId["spiderwebsash"] = 460;
            ClassId["uvc"] = ClassId["vampirefangbelt"] = 461;
            ClassId["umc"] = ClassId["mithrilcoil"] = 462;
            ClassId["utc"] = ClassId["trollbelt"] = 463;
            ClassId["uhc"] = ClassId["colossusgirdle"] = 464;
            ClassId["uh9"] = ClassId["bonevisage"] = 465;
            ClassId["ush"] = ClassId["trollnest"] = 466;
            ClassId["upk"] = ClassId["bladebarrier"] = 467;
            ClassId["dr6"] = ClassId["alphahelm"] = 468;
            ClassId["dr7"] = ClassId["griffonheaddress"] = 469;
            ClassId["dr8"] = ClassId["hunter'sguise"] = 470;
            ClassId["dr9"] = ClassId["sacredfeathers"] = 471;
            ClassId["dra"] = ClassId["totemicmask"] = 472;
            ClassId["ba6"] = ClassId["jawbonevisor"] = 473;
            ClassId["ba7"] = ClassId["lionhelm"] = 474;
            ClassId["ba8"] = ClassId["ragemask"] = 475;
            ClassId["ba9"] = ClassId["savagehelmet"] = 476;
            ClassId["baa"] = ClassId["slayerguard"] = 477;
            ClassId["pa6"] = ClassId["akarantarge"] = 478;
            ClassId["pa7"] = ClassId["akaranrondache"] = 479;
            ClassId["pa8"] = ClassId["protectorshield"] = 480;
            ClassId["pa9"] = ClassId["gildedshield"] = 481;
            ClassId["paa"] = ClassId["royalshield"] = 482;
            ClassId["ne6"] = ClassId["mummifiedtrophy"] = 483;
            ClassId["ne7"] = ClassId["fetishtrophy"] = 484;
            ClassId["ne8"] = ClassId["sextontrophy"] = 485;
            ClassId["ne9"] = ClassId["cantortrophy"] = 486;
            ClassId["nea"] = ClassId["hierophanttrophy"] = 487;
            ClassId["drb"] = ClassId["bloodspirit"] = 488;
            ClassId["drc"] = ClassId["sunspirit"] = 489;
            ClassId["drd"] = ClassId["earthspirit"] = 490;
            ClassId["dre"] = ClassId["skyspirit"] = 491;
            ClassId["drf"] = ClassId["dreamspirit"] = 492;
            ClassId["bab"] = ClassId["carnagehelm"] = 493;
            ClassId["bac"] = ClassId["furyvisor"] = 494;
            ClassId["bad"] = ClassId["destroyerhelm"] = 495;
            ClassId["bae"] = ClassId["conquerorcrown"] = 496;
            ClassId["baf"] = ClassId["guardiancrown"] = 497;
            ClassId["pab"] = ClassId["sacredtarge"] = 498;
            ClassId["pac"] = ClassId["sacredrondache"] = 499;
            ClassId["pad"] = ClassId["kurastshield"] = 500;
            ClassId["pae"] = ClassId["zakarumshield"] = 501;
            ClassId["paf"] = ClassId["vortexshield"] = 502;
            ClassId["neb"] = ClassId["minionskull"] = 503;
            ClassId["neg"] = ClassId["hellspawnskull"] = 504;
            ClassId["ned"] = ClassId["overseerskull"] = 505;
            ClassId["nee"] = ClassId["succubusskull"] = 506;
            ClassId["nef"] = ClassId["bloodlordskull"] = 507;
            ClassId["elx"] = ClassId["elixir"] = 508;
            ClassId["hpo"] = 509;
            ClassId["mpo"] = 510;
            ClassId["hpf"] = 511;
            ClassId["mpf"] = 512;
            ClassId["vps"] = ClassId["staminapotion"] = 513;
            ClassId["yps"] = ClassId["antidotepotion"] = 514;
            ClassId["rvs"] = ClassId["rejuvenationpotion"] = 515;
            ClassId["rvl"] = ClassId["fullrejuvenationpotion"] = 516;
            ClassId["wms"] = ClassId["thawingpotion"] = 517;
            ClassId["tbk"] = ClassId["tomeoftownportal"] = 518;
            ClassId["ibk"] = ClassId["tomeofidentify"] = 519;
            ClassId["amu"] = ClassId["amulet"] = 520;
            ClassId["vip"] = ClassId["topofthehoradricstaff"] = 521;
            ClassId["rin"] = ClassId["ring"] = 522;
            ClassId["gld"] = ClassId["gold"] = 523;
            ClassId["bks"] = ClassId["scrollofinifuss"] = 524;
            ClassId["bkd"] = ClassId["keytothecairnstones"] = 525;
            ClassId["aqv"] = ClassId["arrows"] = 526;
            ClassId["tch"] = ClassId["torch"] = 527;
            ClassId["cqv"] = ClassId["bolts"] = 528;
            ClassId["tsc"] = ClassId["scrolloftownportal"] = 529;
            ClassId["isc"] = ClassId["scrollofidentify"] = 530;
            ClassId["hrt"] = ClassId["heart"] = 531;
            ClassId["brz"] = ClassId["brain"] = 532;
            ClassId["jaw"] = ClassId["jawbone"] = 533;
            ClassId["eyz"] = ClassId["eye"] = 534;
            ClassId["hrn"] = ClassId["horn"] = 535;
            ClassId["tal"] = ClassId["tail"] = 536;
            ClassId["flg"] = ClassId["flag"] = 537;
            ClassId["fng"] = ClassId["fang"] = 538;
            ClassId["qll"] = ClassId["quill"] = 539;
            ClassId["sol"] = ClassId["soul"] = 540;
            ClassId["scz"] = ClassId["scalp"] = 541;
            ClassId["spe"] = ClassId["spleen"] = 542;
            ClassId["key"] = 543;
            ClassId["luv"] = ClassId["theblacktowerkey"] = 544;
            ClassId["xyz"] = ClassId["potionoflife"] = 545;
            ClassId["j34"] = ClassId["ajadefigurine"] = 546;
            ClassId["g34"] = ClassId["thegoldenbird"] = 547;
            ClassId["bbb"] = ClassId["lamesen'stome"] = 548;
            ClassId["box"] = ClassId["horadriccube"] = 549;
            ClassId["tr1"] = ClassId["horadricscroll"] = 550;
            ClassId["mss"] = ClassId["mephisto'ssoulstone"] = 551;
            ClassId["ass"] = ClassId["bookofskill"] = 552;
            ClassId["qey"] = ClassId["khalim'seye"] = 553;
            ClassId["qhr"] = ClassId["khalim'sheart"] = 554;
            ClassId["qbr"] = ClassId["khalim'sbrain"] = 555;
            ClassId["ear"] = 556;
            ClassId["gcv"] = ClassId["chippedamethyst"] = 557;
            ClassId["gfv"] = ClassId["flawedamethyst"] = 558;
            ClassId["gsv"] = ClassId["amethyst"] = 559;
            ClassId["gzv"] = ClassId["flawlessamethyst"] = 560;
            ClassId["gpv"] = ClassId["perfectamethyst"] = 561;
            ClassId["gcy"] = ClassId["chippedtopaz"] = 562;
            ClassId["gfy"] = ClassId["flawedtopaz"] = 563;
            ClassId["gsy"] = ClassId["topaz"] = 564;
            ClassId["gly"] = ClassId["flawlesstopaz"] = 565;
            ClassId["gpy"] = ClassId["perfecttopaz"] = 566;
            ClassId["gcb"] = ClassId["chippedsapphire"] = 567;
            ClassId["gfb"] = ClassId["flawedsapphire"] = 568;
            ClassId["gsb"] = ClassId["sapphire"] = 569;
            ClassId["glb"] = ClassId["flawlesssapphire"] = 570;
            ClassId["gpb"] = ClassId["perfectsapphire"] = 571;
            ClassId["gcg"] = ClassId["chippedemerald"] = 572;
            ClassId["gfg"] = ClassId["flawedemerald"] = 573;
            ClassId["gsg"] = ClassId["emerald"] = 574;
            ClassId["glg"] = ClassId["flawlessemerald"] = 575;
            ClassId["gpg"] = ClassId["perfectemerald"] = 576;
            ClassId["gcr"] = ClassId["chippedruby"] = 577;
            ClassId["gfr"] = ClassId["flawedruby"] = 578;
            ClassId["gsr"] = ClassId["ruby"] = 579;
            ClassId["glr"] = ClassId["flawlessruby"] = 580;
            ClassId["gpr"] = ClassId["perfectruby"] = 581;
            ClassId["gcw"] = ClassId["chippeddiamond"] = 582;
            ClassId["gfw"] = ClassId["flaweddiamond"] = 583;
            ClassId["gsw"] = ClassId["diamond"] = 584;
            ClassId["glw"] = ClassId["flawlessdiamond"] = 585;
            ClassId["gpw"] = ClassId["perfectdiamond"] = 586;
            ClassId["hp1"] = ClassId["minorhealingpotion"] = 587;
            ClassId["hp2"] = ClassId["lighthealingpotion"] = 588;
            ClassId["hp3"] = ClassId["healingpotion"] = 589;
            ClassId["hp4"] = ClassId["greaterhealingpotion"] = 590;
            ClassId["hp5"] = ClassId["superhealingpotion"] = 591;
            ClassId["mp1"] = ClassId["minormanapotion"] = 592;
            ClassId["mp2"] = ClassId["lightmanapotion"] = 593;
            ClassId["mp3"] = ClassId["manapotion"] = 594;
            ClassId["mp4"] = ClassId["greatermanapotion"] = 595;
            ClassId["mp5"] = ClassId["supermanapotion"] = 596;
            ClassId["skc"] = ClassId["chippedskull"] = 597;
            ClassId["skf"] = ClassId["flawedskull"] = 598;
            ClassId["sku"] = ClassId["skull"] = 599;
            ClassId["skl"] = ClassId["flawlessskull"] = 600;
            ClassId["skz"] = ClassId["perfectskull"] = 601;
            ClassId["hrb"] = ClassId["herb"] = 602;
            ClassId["cm1"] = ClassId["smallcharm"] = 603;
            ClassId["cm2"] = ClassId["largecharm"] = 604;
            ClassId["cm3"] = ClassId["grandcharm"] = 605;
            ClassId["rps"] = 606;
            ClassId["rpl"] = 607;
            ClassId["bps"] = 608;
            ClassId["bpl"] = 609;
            ClassId["r01"] = ClassId["elrune"] = 610;
            ClassId["r02"] = ClassId["eldrune"] = 611;
            ClassId["r03"] = ClassId["tirrune"] = 612;
            ClassId["r04"] = ClassId["nefrune"] = 613;
            ClassId["r05"] = ClassId["ethrune"] = 614;
            ClassId["r06"] = ClassId["ithrune"] = 615;
            ClassId["r07"] = ClassId["talrune"] = 616;
            ClassId["r08"] = ClassId["ralrune"] = 617;
            ClassId["r09"] = ClassId["ortrune"] = 618;
            ClassId["r10"] = ClassId["thulrune"] = 619;
            ClassId["r11"] = ClassId["amnrune"] = 620;
            ClassId["r12"] = ClassId["solrune"] = 621;
            ClassId["r13"] = ClassId["shaelrune"] = 622;
            ClassId["r14"] = ClassId["dolrune"] = 623;
            ClassId["r15"] = ClassId["helrune"] = 624;
            ClassId["r16"] = ClassId["iorune"] = 625;
            ClassId["r17"] = ClassId["lumrune"] = 626;
            ClassId["r18"] = ClassId["korune"] = 627;
            ClassId["r19"] = ClassId["falrune"] = 628;
            ClassId["r20"] = ClassId["lemrune"] = 629;
            ClassId["r21"] = ClassId["pulrune"] = 630;
            ClassId["r22"] = ClassId["umrune"] = 631;
            ClassId["r23"] = ClassId["malrune"] = 632;
            ClassId["r24"] = ClassId["istrune"] = 633;
            ClassId["r25"] = ClassId["gulrune"] = 634;
            ClassId["r26"] = ClassId["vexrune"] = 635;
            ClassId["r27"] = ClassId["ohmrune"] = 636;
            ClassId["r28"] = ClassId["lorune"] = 637;
            ClassId["r29"] = ClassId["surrune"] = 638;
            ClassId["r30"] = ClassId["berrune"] = 639;
            ClassId["r31"] = ClassId["jahrune"] = 640;
            ClassId["r32"] = ClassId["chamrune"] = 641;
            ClassId["r33"] = ClassId["zodrune"] = 642;
            ClassId["jew"] = ClassId["jewel"] = 643;
            ClassId["ice"] = ClassId["malah'spotion"] = 644;
            ClassId["0sc"] = ClassId["scrollofknowledge"] = 645;
            ClassId["tr2"] = ClassId["scrollofresistance"] = 646;
            ClassId["pk1"] = ClassId["keyofterror"] = 647;
            ClassId["pk2"] = ClassId["keyofhate"] = 648;
            ClassId["pk3"] = ClassId["keyofdestruction"] = 649;
            ClassId["dhn"] = ClassId["diablo'shorn"] = 650;
            ClassId["bey"] = ClassId["baal'seye"] = 651;
            ClassId["mbr"] = ClassId["mephisto'sbrain"] = 652;
            ClassId["toa"] = ClassId["tokenofabsolution"] = 653;
            ClassId["tes"] = ClassId["twistedessenceofsuffering"] = 654;
            ClassId["ceh"] = ClassId["chargedessenceofhatred"] = 655;
            ClassId["bet"] = ClassId["burningessenceofterror"] = 656;
            ClassId["fed"] = ClassId["festeringessenceofdestruction"] = 657;
            ClassId["std"] = ClassId["standardofheroes"] = 658;

            #endregion

            #region AliasClass

            Class["normal"] = 0;
            Class["exceptional"] = 1;
            Class["elite"] = 2;

            #endregion

            #region AliasQuality

            Quality["lowquality"] = 1;
            Quality["normal"] = 2;
            Quality["superior"] = 3;
            Quality["magic"] = 4;
            Quality["set"] = 5;
            Quality["rare"] = 6;
            Quality["unique"] = 7;
            Quality["crafted"] = 8;

            #endregion

            #region AliasFlag

            Flag["identified"] = 0x10;
            Flag["eth"] = Flag["ethereal"] = 0x400000;
            Flag["runeword"] = 0x4000000;

            #endregion AliasFlag

            #region AliasColor

            Color["black"] = 3;
            Color["white"] = 20;
            Color["orange"] = 19;
            Color["lightyellow"] = 13;
            Color["lightred"] = 7;
            Color["lightgold"] = 15;
            Color["lightblue"] = 4;
            Color["lightpurple"] = 17;
            Color["crystalblue"] = 6;
            Color["crystalred"] = 9;
            Color["crystalgreen"] = 12;
            Color["darkyellow"] = 14;
            Color["darkred"] = 8;
            Color["darkgold"] = 16;
            Color["darkgreen"] = 11;
            Color["darkblue"] = 5;

            #endregion AliasColor

            #region AliasStat

            Stat["strength"] = (0, null);
            Stat["energy"] = (1, null);
            Stat["dexterity"] = (2, null);
            Stat["vitality"] = (3, null);
            Stat["statpts"] = (4, null);
            Stat["newskills"] = (5, null);
            Stat["hitpoints"] = (6, null);
            Stat["maxhp"] = (7, null);
            Stat["mana"] = (8, null);
            Stat["maxmana"] = (9, null);
            Stat["stamina"] = (10, null);
            Stat["maxstamina"] = (11, null);
            Stat["level"] = (12, null);
            Stat["experience"] = (13, null);
            Stat["gold"] = (14, null);
            Stat["goldbank"] = (15, null);
            Stat["itemarmorpercent"] = Stat["enhanceddefense"] = (16, 0);
            Stat["itemmaxdamagepercent"] = (17, 0);
            Stat["itemmindamagepercent"] = Stat["enhanceddamage"] = (18, 0);
            Stat["tohit"] = (19, null);
            Stat["toblock"] = (20, null);
            Stat["plusmindamage"] = (21, 1);
            Stat["mindamage"] = (21, null);
            Stat["plusmaxdamage"] = (22, 1);
            Stat["maxdamage"] = (22, null);
            Stat["secondarymindamage"] = (23, null);
            Stat["secondarymaxdamage"] = (24, null);
            Stat["damagepercent"] = (25, null);
            Stat["manarecovery"] = (26, null);
            Stat["manarecoverybonus"] = (27, null);
            Stat["staminarecoverybonus"] = (28, null);
            Stat["lastexp"] = (29, null);
            Stat["nextexp"] = (30, null);

            Stat["armorclass"] = Stat["defense"] = (31, null);
            Stat["plusdefense"] = (31, 0);

            Stat["armorclassvsmissile"] = (32, null);
            Stat["armorclassvshth"] = (33, null);
            Stat["normaldamagereduction"] = (34, null);
            Stat["magicdamagereduction"] = (35, null);
            Stat["damageresist"] = (36, null);
            Stat["magicresist"] = (37, null);
            Stat["maxmagicresist"] = (38, null);
            Stat["fireresist"] = (39, null);
            Stat["maxfireresist"] = (40, null);
            Stat["lightresist"] = (41, null);
            Stat["maxlightresist"] = (42, null);
            Stat["coldresist"] = (43, null);
            Stat["maxcoldresist"] = (44, null);
            Stat["poisonresist"] = (45, null);
            Stat["maxpoisonresist"] = (46, null);
            Stat["damageaura"] = (47, null);
            Stat["firemindam"] = (48, null);
            Stat["firemaxdam"] = (49, null);
            Stat["lightmindam"] = (50, null);
            Stat["lightmaxdam"] = (51, null);
            Stat["magicmindam"] = (52, null);
            Stat["magicmaxdam"] = (53, null);
            Stat["coldmindam"] = (54, null);
            Stat["coldmaxdam"] = (55, null);
            Stat["coldlength"] = (56, null);
            Stat["poisondamage"] = (57, 1);
            Stat["poisonmindam"] = (57, null);
            Stat["poisonmaxdam"] = (58, null);
            Stat["poisonlength"] = (59, null);
            Stat["lifedrainmindam"] = Stat["lifeleech"] = (60, null);
            Stat["lifedrainmaxdam"] = (61, null);
            Stat["manadrainmindam"] = Stat["manaleech"] = (62, null);
            Stat["manadrainmaxdam"] = (63, null);
            Stat["stamdrainmindam"] = (64, null);
            Stat["stamdrainmaxdam"] = (65, null);
            Stat["stunlength"] = (66, null);
            Stat["velocitypercent"] = (67, null);
            Stat["attackrate"] = (68, null);
            Stat["otheranimrate"] = (69, null);
            Stat["quantity"] = (70, null);
            Stat["value"] = (71, null);
            Stat["durability"] = (72, null);
            Stat["maxdurability"] = (73, null);
            Stat["hpregen"] = (74, null);
            Stat["itemmaxdurabilitypercent"] = (75, null);
            Stat["itemmaxhppercent"] = (76, null);
            Stat["itemmaxmanapercent"] = (77, null);
            Stat["itemattackertakesdamage"] = (78, null);
            Stat["itemgoldbonus"] = (79, null);
            Stat["itemmagicbonus"] = (80, null);
            Stat["itemknockback"] = (81, null);
            Stat["itemtimeduration"] = (82, null);

            Stat["itemaddclassskills"] = (83, null);
            Stat["itemaddamazonskills"] = Stat["amazonskills"] = (83, 0);
            Stat["itemaddsorceressskills"] = Stat["sorceressskills"] = (83, 1);
            Stat["itemaddnecromancerskills"] = Stat["necromancerskills"] = (83, 2);
            Stat["itemaddpaladinskills"] = Stat["paladinskills"] = (83, 3);
            Stat["itemaddbarbarianskills"] = Stat["barbarianskills"] = (83, 4);
            Stat["itemadddruidskills"] = Stat["druidskills"] = (83, 5);
            Stat["itemaddassassinskills"] = Stat["assassinskills"] = (83, 6);

            Stat["unsentparam1"] = (84, null);
            Stat["itemaddexperience"] = (85, null);
            Stat["itemhealafterkill"] = (86, null);
            Stat["itemreducedprices"] = (87, null);
            Stat["itemdoubleherbduration"] = (88, null);
            Stat["itemlightradius"] = (89, null);
            Stat["itemlightcolor"] = (90, null);
            Stat["itemreqpercent"] = (91, null);
            Stat["itemlevelreq"] = (92, null);
            Stat["itemfasterattackrate"] = Stat["ias"] = (93, null);
            Stat["itemlevelreqpct"] = (94, null);
            Stat["lastblockframe"] = (95, null);
            Stat["itemfastermovevelocity"] = Stat["frw"] = (96, null);

            // oskill
            Stat["itemnonclassskill"] = (97, null);
            // Amazon
            Stat["plusskillcriticalstrike"] = (97, 9);
            Stat["plusskillguidedarrow"] = (97, 22);
            // Sorceress
            Stat["plusskillteleport"] = (97, 54);
            // Barbarian
            Stat["plusskillbattleorders"] = (97, 149);
            Stat["plusskillbattlecommand"] = (97, 155);
            Stat["plusskillbattlecry"] = (97, 146);
            // Druid
            Stat["plusskillwerewolf"] = (97, 223);
            Stat["plusskillshapeshifting"] = Stat["plusskilllycanthropy"] = (97, 224);
            Stat["plusskillsummonspiritwolf"] = (97, 227);

            Stat["state"] = (98, null);
            Stat["itemfastergethitrate"] = Stat["fhr"] = (99, null);
            Stat["monsterplayercount"] = (100, null);
            Stat["skillpoisonoverridelength"] = (101, null);
            Stat["itemfasterblockrate"] = Stat["fbr"] = (102, null);
            Stat["skillbypassundead"] = (103, null);
            Stat["skillbypassdemons"] = (104, null);
            Stat["itemfastercastrate"] = Stat["fcr"] = (105, null);
            Stat["skillbypassbeasts"] = (106, null);

            Stat["itemsingleskill"] = (107, null);
            // Amazon skills
            Stat["skillmagicarrow"] = (107, 6);
            Stat["skillfirearrow"] = (107, 7);
            Stat["skillinnersight"] = (107, 8);
            Stat["skillcriticalstrike"] = (107, 9);
            Stat["skilljab"] = (107, 10);
            Stat["skillcoldarrow"] = (107, 11);
            Stat["skillmultipleshot"] = (107, 12);
            Stat["skilldodge"] = (107, 13);
            Stat["skillpowerstrike"] = (107, 14);
            Stat["skillpoisonjavelin"] = (107, 15);
            Stat["skillexplodingarrow"] = (107, 16);
            Stat["skillslowmissiles"] = (107, 17);
            Stat["skillavoid"] = (107, 18);
            Stat["skillimpale"] = (107, 19);
            Stat["skilllightningbolt"] = (107, 20);
            Stat["skillicearrow"] = (107, 21);
            Stat["skillguidedarrow"] = (107, 22);
            Stat["skillpenetrate"] = (107, 23);
            Stat["skillchargedstrike"] = (107, 24);
            Stat["skillplaguejavelin"] = (107, 25);
            Stat["skillstrafe"] = (107, 26);
            Stat["skillimmolationarrow"] = (107, 27);
            Stat["skilldecoy"] = (107, 28);
            Stat["skillevade"] = (107, 29);
            Stat["skillfend"] = (107, 30);
            Stat["skillfreezingarrow"] = (107, 31);
            Stat["skillvalkyrie"] = (107, 32);
            Stat["skillpierce"] = (107, 33);
            Stat["skilllightningstrike"] = (107, 34);
            Stat["skilllightningfury"] = (107, 35);
            // Sorceress skills
            Stat["skillfirebolt"] = (107, 36);
            Stat["skillwarmth"] = (107, 37);
            Stat["skillchargedbolt"] = (107, 38);
            Stat["skillicebolt"] = (107, 39);
            Stat["skillfrozenarmor"] = (107, 40);
            Stat["skillinferno"] = (107, 41);
            Stat["skillstaticfield"] = (107, 42);
            Stat["skilltelekinesis"] = (107, 43);
            Stat["skillfrostnova"] = (107, 44);
            Stat["skilliceblast"] = (107, 45);
            Stat["skillblaze"] = (107, 46);
            Stat["skillfireball"] = (107, 47);
            Stat["skillnova"] = (107, 48);
            Stat["skilllightning"] = (107, 49);
            Stat["skillshiverarmor"] = (107, 50);
            Stat["skillfirewall"] = (107, 51);
            Stat["skillenchant"] = (107, 52);
            Stat["skillchainlightning"] = (107, 53);
            Stat["skillteleport"] = (107, 54);
            Stat["skillglacialspike"] = (107, 55);
            Stat["skillmeteor"] = (107, 56);
            Stat["skillthunderstorm"] = (107, 57);
            Stat["skillenergyshield"] = (107, 58);
            Stat["skillblizzard"] = (107, 59);
            Stat["skillchillingarmor"] = (107, 60);
            Stat["skillfiremastery"] = (107, 61);
            Stat["skillhydra"] = (107, 62);
            Stat["skilllightningmastery"] = (107, 63);
            Stat["skillfrozenorb"] = (107, 64);
            Stat["skillcoldmastery"] = (107, 65);
            // Necromancer skills
            Stat["skillamplifydamage"] = (107, 66);
            Stat["skillteeth"] = (107, 67);
            Stat["skillbonearmor"] = (107, 68);
            Stat["skillskeletonmastery"] = (107, 69);
            Stat["skillraiseskeleton"] = (107, 70);
            Stat["skilldimvision"] = (107, 71);
            Stat["skillweaken"] = (107, 72);
            Stat["skillpoisondagger"] = (107, 73);
            Stat["skillcorpseexplosion"] = (107, 74);
            Stat["skillclaygolem"] = (107, 75);
            Stat["skillironmaiden"] = (107, 76);
            Stat["skillterror"] = (107, 77);
            Stat["skillbonewall"] = (107, 78);
            Stat["skillgolemmastery"] = (107, 79);
            Stat["skillskeletalmage"] = (107, 80);
            Stat["skillconfuse"] = (107, 81);
            Stat["skilllifetap"] = (107, 82);
            Stat["skillpoisonexplosion"] = (107, 83);
            Stat["skillbonespear"] = (107, 84);
            Stat["skillbloodgolem"] = (107, 85);
            Stat["skillattract"] = (107, 86);
            Stat["skilldecrepify"] = (107, 87);
            Stat["skillboneprison"] = (107, 88);
            Stat["skillsummonresist"] = (107, 89);
            Stat["skillirongolem"] = (107, 90);
            Stat["skilllowerresist"] = (107, 91);
            Stat["skillpoisonnova"] = (107, 92);
            Stat["skillbonespirit"] = (107, 93);
            Stat["skillfiregolem"] = (107, 94);
            Stat["skillrevive"] = (107, 95);
            // Paladin skills
            Stat["skillsacrifice"] = (107, 96);
            Stat["skillsmite"] = (107, 97);
            Stat["skillmight"] = (107, 98);
            Stat["skillprayer"] = (107, 99);
            Stat["skillresistfire"] = (107, 100);
            Stat["skillholybolt"] = (107, 101);
            Stat["skillholyfire"] = (107, 102);
            Stat["skillthorns"] = (107, 103);
            Stat["skilldefiance"] = (107, 104);
            Stat["skillresistcold"] = (107, 105);
            Stat["skillzeal"] = (107, 106);
            Stat["skillcharge"] = (107, 107);
            Stat["skillblessedaim"] = (107, 108);
            Stat["skillcleansing"] = (107, 109);
            Stat["skillresistlightning"] = (107, 110);
            Stat["skillvengeance"] = (107, 111);
            Stat["skillblessedhammer"] = (107, 112);
            Stat["skillconcentration"] = (107, 113);
            Stat["skillholyfreeze"] = (107, 114);
            Stat["skillvigor"] = (107, 115);
            Stat["skillconversion"] = (107, 116);
            Stat["skillholyshield"] = (107, 117);
            Stat["skillholyshock"] = (107, 118);
            Stat["skillsanctuary"] = (107, 119);
            Stat["skillmeditation"] = (107, 120);
            Stat["skillfistoftheheavens"] = (107, 121);
            Stat["skillfanaticism"] = (107, 122);
            Stat["skillconviction"] = (107, 123);
            Stat["skillredemption"] = (107, 124);
            Stat["skillsalvation"] = (107, 125);
            // Barbarian skills
            Stat["skillbash"] = (107, 126);
            Stat["skillswordmastery"] = (107, 127);
            Stat["skillaxemastery"] = (107, 128);
            Stat["skillmacemastery"] = (107, 129);
            Stat["skillhowl"] = (107, 130);
            Stat["skillfindpotion"] = (107, 131);
            Stat["skillleap"] = (107, 132);
            Stat["skilldoubleswing"] = (107, 133);
            Stat["skillpolearmmastery"] = (107, 134);
            Stat["skillthrowingmastery"] = (107, 135);
            Stat["skillspearmastery"] = (107, 136);
            Stat["skilltaunt"] = (107, 137);
            Stat["skillshout"] = (107, 138);
            Stat["skillstun"] = (107, 139);
            Stat["skilldoublethrow"] = (107, 140);
            Stat["skillincreasedstamina"] = (107, 141);
            Stat["skillfinditem"] = (107, 142);
            Stat["skillleapattack"] = (107, 143);
            Stat["skillconcentrate"] = (107, 144);
            Stat["skillironskin"] = (107, 145);
            Stat["skillbattlecry"] = (107, 146);
            Stat["skillfrenzy"] = (107, 147);
            Stat["skillincreasedspeed"] = (107, 148);
            Stat["skillbattleorders"] = (107, 149);
            Stat["skillgrimward"] = (107, 150);
            Stat["skillwhirlwind"] = (107, 151);
            Stat["skillberserk"] = (107, 152);
            Stat["skillnaturalresistance"] = (107, 153);
            Stat["skillwarcry"] = (107, 154);
            Stat["skillbattlecommand"] = (107, 155);
            // Druid skills
            Stat["skillraven"] = (107, 221);
            Stat["skillpoisoncreeper"] = (107, 222);
            Stat["skillwerewolf"] = (107, 223);
            Stat["skilllycanthropy"] = (107, 224);
            Stat["skillfirestorm"] = (107, 225);
            Stat["skilloaksage"] = (107, 226);
            Stat["skillsummonspiritwolf"] = (107, 227);
            Stat["skillwerebear"] = (107, 228);
            Stat["skillmoltenboulder"] = (107, 229);
            Stat["skillarcticblast"] = (107, 230);
            Stat["skillfissure"] = (107, 231);
            Stat["skillferalrage"] = (107, 232);
            Stat["skillmaul"] = (107, 233);
            Stat["skillcarrionvine"] = (107, 234);
            Stat["skillcyclonearmor"] = (107, 235);
            Stat["skillheartofwolverine"] = (107, 236);
            Stat["skillsummondirewolf"] = (107, 237);
            Stat["skillrabies"] = (107, 238);
            Stat["skillfireclaws"] = (107, 239);
            Stat["skilltwister"] = (107, 240);
            Stat["skillsolarcreeper"] = (107, 241);
            Stat["skillhunger"] = (107, 242);
            Stat["skillshockwave"] = (107, 243);
            Stat["skillvolcano"] = (107, 244);
            Stat["skilltornado"] = (107, 245);
            Stat["skillspiritofbarbs"] = (107, 246);
            Stat["skillsummongrizzly"] = (107, 247);
            Stat["skillfury"] = (107, 248);
            Stat["skillarmageddon"] = (107, 249);
            Stat["skillhurricane"] = (107, 250);
            // Assassin skills
            Stat["skillfireblast"] = (107, 251);
            Stat["skillclawmastery"] = (107, 252);
            Stat["skillpsychichammer"] = (107, 253);
            Stat["skilltigerstrike"] = (107, 254);
            Stat["skilldragontalon"] = (107, 255);
            Stat["skillshockweb"] = (107, 256);
            Stat["skillbladesentinel"] = (107, 257);
            Stat["skillburstofspeed"] = (107, 258);
            Stat["skillfistsoffire"] = (107, 259);
            Stat["skilldragonclaw"] = (107, 260);
            Stat["skillchargedboltsentry"] = (107, 261);
            Stat["skillwakeoffire"] = (107, 262);
            Stat["skillweaponblock"] = (107, 263);
            Stat["skillcloakofshadows"] = (107, 264);
            Stat["skillcobrastrike"] = (107, 265);
            Stat["skillbladefury"] = (107, 266);
            Stat["skillfade"] = (107, 267);
            Stat["skillshadowwarrior"] = (107, 268);
            Stat["skillclawsofthunder"] = (107, 269);
            Stat["skilldragontail"] = (107, 270);
            Stat["skilllightningsentry"] = (107, 271);
            Stat["skillwakeofinferno"] = (107, 272);
            Stat["skillmindblast"] = (107, 273);
            Stat["skillbladesofice"] = (107, 274);
            Stat["skilldragonflight"] = (107, 275);
            Stat["skilldeathsentry"] = (107, 276);
            Stat["skillbladeshield"] = (107, 277);
            Stat["skillvenom"] = (107, 278);
            Stat["skillshadowmaster"] = (107, 279);
            Stat["skillphoenixstrike"] = (107, 280);

            Stat["itemrestinpeace"] = (108, null);
            Stat["curseresistance"] = (109, null);
            Stat["itempoisonlengthresist"] = (110, null);
            Stat["itemnormaldamage"] = (111, null);
            Stat["itemhowl"] = (112, null);
            Stat["itemstupidity"] = (113, null);
            Stat["itemdamagetomana"] = (114, null);
            Stat["itemignoretargetac"] = (115, null);
            Stat["itemfractionaltargetac"] = (116, null);
            Stat["itempreventheal"] = (117, null);
            Stat["itemhalffreezeduration"] = (118, null);
            Stat["itemtohitpercent"] = (119, null);
            Stat["itemdamagetargetac"] = (120, null);
            Stat["itemdemondamagepercent"] = (121, null);
            Stat["itemundeaddamagepercent"] = (122, null);
            Stat["itemdemontohit"] = (123, null);
            Stat["itemundeadtohit"] = (124, null);
            Stat["itemthrowable"] = (125, null);
            Stat["itemelemskill"] = (126, null);
            Stat["itemallskills"] = (127, null);
            Stat["itemattackertakeslightdamage"] = (128, null);
            Stat["ironmaidenlevel"] = (129, null);
            Stat["lifetaplevel"] = (130, null);
            Stat["thornspercent"] = (131, null);
            Stat["bonearmor"] = (132, null);
            Stat["bonearmormax"] = (133, null);
            Stat["itemfreeze"] = (134, null);
            Stat["itemopenwounds"] = (135, null);
            Stat["itemcrushingblow"] = (136, null);
            Stat["itemkickdamage"] = (137, null);
            Stat["itemmanaafterkill"] = (138, null);
            Stat["itemhealafterdemonkill"] = (139, null);
            Stat["itemextrablood"] = (140, null);
            Stat["itemdeadlystrike"] = (141, null);
            Stat["itemabsorbfirepercent"] = (142, null);
            Stat["itemabsorbfire"] = (143, null);
            Stat["itemabsorblightpercent"] = (144, null);
            Stat["itemabsorblight"] = (145, null);
            Stat["itemabsorbmagicpercent"] = (146, null);
            Stat["itemabsorbmagic"] = (147, null);
            Stat["itemabsorbcoldpercent"] = (148, null);
            Stat["itemabsorbcold"] = (149, null);
            Stat["itemslow"] = (150, null);

            Stat["itemaura"] = (151, null);
            Stat["mightaura"] = (151, 98);
            Stat["holyfireaura"] = (151, 102);
            Stat["thornsaura"] = (151, 103);
            Stat["defianceaura"] = (151, 104);
            Stat["concentrationaura"] = (151, 113);
            Stat["holyfreezeaura"] = (151, 114);
            Stat["vigoraura"] = (151, 115);
            Stat["holyshockaura"] = (151, 118);
            Stat["sanctuaryaura"] = (151, 119);
            Stat["meditationaura"] = (151, 120);
            Stat["fanaticismaura"] = (151, 122);
            Stat["convictionaura"] = (151, 123);
            Stat["redemptionaura"] = (151, 124);

            Stat["itemindestructible"] = (152, null);
            Stat["itemcannotbefrozen"] = (153, null);
            Stat["itemstaminadrainpct"] = (154, null);
            Stat["itemreanimate"] = (155, null);
            Stat["itempierce"] = (156, null);
            Stat["itemmagicarrow"] = (157, null);
            Stat["itemexplosivearrow"] = (158, null);
            Stat["itemthrowmindamage"] = (159, null);
            Stat["itemthrowmaxdamage"] = (160, null);
            Stat["itemskillhandofathena"] = (161, null);
            Stat["itemskillstaminapercent"] = (162, null);
            Stat["itemskillpassivestaminapercent"] = (163, null);
            Stat["itemskillconcentration"] = (164, null);
            Stat["itemskillenchant"] = (165, null);
            Stat["itemskillpierce"] = (166, null);
            Stat["itemskillconviction"] = (167, null);
            Stat["itemskillchillingarmor"] = (168, null);
            Stat["itemskillfrenzy"] = (169, null);
            Stat["itemskilldecrepify"] = (170, null);
            Stat["itemskillarmorpercent"] = (171, null);
            Stat["alignment"] = (172, null);
            Stat["target0"] = (173, null);
            Stat["target1"] = (174, null);
            Stat["goldlost"] = (175, null);
            Stat["conversionlevel"] = (176, null);
            Stat["conversionmaxhp"] = (177, null);
            Stat["unitdooverlay"] = (178, null);
            Stat["attackvsmontype"] = (179, null);
            Stat["damagevsmontype"] = (180, null);
            Stat["fade"] = (181, null);
            Stat["armoroverridepercent"] = (182, null);
            Stat["unused183"] = (183, null);
            Stat["unused184"] = (184, null);
            Stat["unused185"] = (185, null);
            Stat["unused186"] = (186, null);
            Stat["unused187"] = (187, null);

            Stat["itemaddskilltab"] = (188, null);
            Stat["itemaddbowandcrossbowskilltab"] = Stat["bowandcrossbowskilltab"] = (188, 0);
            Stat["itemaddpassiveandmagicskilltab"] = Stat["passiveandmagicskilltab"] = (188, 1);
            Stat["itemaddjavelinandspearskilltab"] = Stat["javelinandspearskilltab"] = (188, 2);
            Stat["itemaddfireskilltab"] = Stat["fireskilltab"] = (188, 8);
            Stat["itemaddlightningskilltab"] = Stat["lightningskilltab"] = (188, 9);
            Stat["itemaddcoldskilltab"] = Stat["coldskilltab"] = (188, 10);
            Stat["itemaddcursesskilltab"] = Stat["cursesskilltab"] = (188, 16);
            Stat["itemaddpoisonandboneskilltab"] = Stat["poisonandboneskilltab"] = (188, 17);
            Stat["itemaddnecromancersummoningskilltab"] =
                Stat["necromancersummoningskilltab"] = (188, 18);
            Stat["itemaddpalicombatskilltab"] = Stat["palicombatskilltab"] = (188, 24);
            Stat["itemaddoffensiveaurasskilltab"] = Stat["offensiveaurasskilltab"] = (188, 25);
            Stat["itemadddefensiveaurasskilltab"] = Stat["defensiveaurasskilltab"] = (188, 26);
            Stat["itemaddbarbcombatskilltab"] = Stat["barbcombatskilltab"] = (188, 32);
            Stat["itemaddmasteriesskilltab"] = Stat["masteriesskilltab"] = (188, 33);
            Stat["itemaddwarcriesskilltab"] = Stat["warcriesskilltab"] = (188, 34);
            Stat["itemadddruidsummoningskilltab"] = Stat["druidsummoningskilltab"] = (188, 40);
            Stat["itemaddshapeshiftingskilltab"] = Stat["shapeshiftingskilltab"] = (188, 41);
            Stat["itemaddelementalskilltab"] = Stat["elementalskilltab"] = (188, 42);
            Stat["itemaddtrapsskilltab"] = Stat["trapsskilltab"] = (188, 48);
            Stat["itemaddshadowdisciplinesskilltab"] = Stat["shadowdisciplinesskilltab"] = (188, 49);
            Stat["itemaddmartialartsskilltab"] = Stat["martialartsskilltab"] = (188, 50);

            Stat["unused189"] = (189, null);
            Stat["unused190"] = (190, null);
            Stat["unused191"] = (191, null);
            Stat["unused192"] = (192, null);
            Stat["unused193"] = (193, null);
            Stat["itemnumsockets"] = Stat["sockets"] = (194, null);
            Stat["itemskillonattack"] = (195, null);
            Stat["itemskillonkill"] = (196, null);
            Stat["itemskillondeath"] = (197, null);

            Stat["itemskillonhit"] = (198, null);
            Stat["amplifydamageonhit"] = (198, 4225);

            Stat["itemskillonlevelup"] = (199, null);
            Stat["unused200"] = (200, null);
            Stat["itemskillongethit"] = (201, null);
            Stat["unused202"] = (202, null);
            Stat["unused203"] = (203, null);

            Stat["itemchargedskill"] = (204, null);
            Stat["teleportcharges"] = (204, 3461);

            Stat["unused204"] = (205, null);
            Stat["unused205"] = (206, null);
            Stat["unused206"] = (207, null);
            Stat["unused207"] = (208, null);
            Stat["unused208"] = (209, null);
            Stat["unused209"] = (210, null);
            Stat["unused210"] = (211, null);
            Stat["unused211"] = (212, null);
            Stat["unused212"] = (213, null);
            Stat["itemarmorperlevel"] = (214, null);
            Stat["itemarmorpercentperlevel"] = (215, null);
            Stat["itemhpperlevel"] = (216, null);
            Stat["itemmanaperlevel"] = (217, null);
            Stat["itemmaxdamageperlevel"] = (218, null);
            Stat["itemmaxdamagepercentperlevel"] = (219, null);
            Stat["itemstrengthperlevel"] = (220, null);
            Stat["itemdexterityperlevel"] = (221, null);
            Stat["itemenergyperlevel"] = (222, null);
            Stat["itemvitalityperlevel"] = (223, null);
            Stat["itemtohitperlevel"] = (224, null);
            Stat["itemtohitpercentperlevel"] = (225, null);
            Stat["itemcolddamagemaxperlevel"] = (226, null);
            Stat["itemfiredamagemaxperlevel"] = (227, null);
            Stat["itemltngdamagemaxperlevel"] = (228, null);
            Stat["itempoisdamagemaxperlevel"] = (229, null);
            Stat["itemresistcoldperlevel"] = (230, null);
            Stat["itemresistfireperlevel"] = (231, null);
            Stat["itemresistltngperlevel"] = (232, null);
            Stat["itemresistpoisperlevel"] = (233, null);
            Stat["itemabsorbcoldperlevel"] = (234, null);
            Stat["itemabsorbfireperlevel"] = (235, null);
            Stat["itemabsorbltngperlevel"] = (236, null);
            Stat["itemabsorbpoisperlevel"] = (237, null);
            Stat["itemthornsperlevel"] = (238, null);
            Stat["itemfindgoldperlevel"] = (239, null);
            Stat["itemfindmagicperlevel"] = (240, null);
            Stat["itemregenstaminaperlevel"] = (241, null);
            Stat["itemstaminaperlevel"] = (242, null);
            Stat["itemdamagedemonperlevel"] = (243, null);
            Stat["itemdamageundeadperlevel"] = (244, null);
            Stat["itemtohitdemonperlevel"] = (245, null);
            Stat["itemtohitundeadperlevel"] = (246, null);
            Stat["itemcrushingblowperlevel"] = (247, null);
            Stat["itemopenwoundsperlevel"] = (248, null);
            Stat["itemkickdamageperlevel"] = (249, null);
            Stat["itemdeadlystrikeperlevel"] = (250, null);
            Stat["itemfindgemsperlevel"] = (251, null);
            Stat["itemreplenishdurability"] = (252, null);
            Stat["itemreplenishquantity"] = (253, null);
            Stat["itemextrastack"] = (254, null);
            Stat["itemfinditem"] = (255, null);
            Stat["itemslashdamage"] = (256, null);
            Stat["itemslashdamagepercent"] = (257, null);
            Stat["itemcrushdamage"] = (258, null);
            Stat["itemcrushdamagepercent"] = (259, null);
            Stat["itemthrustdamage"] = (260, null);
            Stat["itemthrustdamagepercent"] = (261, null);
            Stat["itemabsorbslash"] = (262, null);
            Stat["itemabsorbcrush"] = (263, null);
            Stat["itemabsorbthrust"] = (264, null);
            Stat["itemabsorbslashpercent"] = (265, null);
            Stat["itemabsorbcrushpercent"] = (266, null);
            Stat["itemabsorbthrustpercent"] = (267, null);
            Stat["itemarmorbytime"] = (268, null);
            Stat["itemarmorpercentbytime"] = (269, null);
            Stat["itemhpbytime"] = (270, null);
            Stat["itemmanabytime"] = (271, null);
            Stat["itemmaxdamagebytime"] = (272, null);
            Stat["itemmaxdamagepercentbytime"] = (273, null);
            Stat["itemstrengthbytime"] = (274, null);
            Stat["itemdexteritybytime"] = (275, null);
            Stat["itemenergybytime"] = (276, null);
            Stat["itemvitalitybytime"] = (277, null);
            Stat["itemtohitbytime"] = (278, null);
            Stat["itemtohitpercentbytime"] = (279, null);
            Stat["itemcolddamagemaxbytime"] = (280, null);
            Stat["itemfiredamagemaxbytime"] = (281, null);
            Stat["itemltngdamagemaxbytime"] = (282, null);
            Stat["itempoisdamagemaxbytime"] = (283, null);
            Stat["itemresistcoldbytime"] = (284, null);
            Stat["itemresistfirebytime"] = (285, null);
            Stat["itemresistltngbytime"] = (286, null);
            Stat["itemresistpoisbytime"] = (287, null);
            Stat["itemabsorbcoldbytime"] = (288, null);
            Stat["itemabsorbfirebytime"] = (289, null);
            Stat["itemabsorbltngbytime"] = (290, null);
            Stat["itemabsorbpoisbytime"] = (291, null);
            Stat["itemfindgoldbytime"] = (292, null);
            Stat["itemfindmagicbytime"] = (293, null);
            Stat["itemregenstaminabytime"] = (294, null);
            Stat["itemstaminabytime"] = (295, null);
            Stat["itemdamagedemonbytime"] = (296, null);
            Stat["itemdamageundeadbytime"] = (297, null);
            Stat["itemtohitdemonbytime"] = (298, null);
            Stat["itemtohitundeadbytime"] = (299, null);
            Stat["itemcrushingblowbytime"] = (300, null);
            Stat["itemopenwoundsbytime"] = (301, null);
            Stat["itemkickdamagebytime"] = (302, null);
            Stat["itemdeadlystrikebytime"] = (303, null);
            Stat["itemfindgemsbytime"] = (304, null);
            Stat["itempiercecold"] = (305, null);
            Stat["itempiercefire"] = (306, null);
            Stat["itempierceltng"] = (307, null);
            Stat["itempiercepois"] = (308, null);
            Stat["itemdamagevsmonster"] = (309, null);
            Stat["itemdamagepercentvsmonster"] = (310, null);
            Stat["itemtohitvsmonster"] = (311, null);
            Stat["itemtohitpercentvsmonster"] = (312, null);
            Stat["itemacvsmonster"] = (313, null);
            Stat["itemacpercentvsmonster"] = (314, null);
            Stat["firelength"] = (315, null);
            Stat["burningmin"] = (316, null);
            Stat["burningmax"] = (317, null);
            Stat["progressivedamage"] = (318, null);
            Stat["progressivesteal"] = (319, null);
            Stat["progressiveother"] = (320, null);
            Stat["progressivefire"] = (321, null);
            Stat["progressivecold"] = (322, null);
            Stat["progressivelightning"] = (323, null);
            Stat["itemextracharges"] = (324, null);
            Stat["progressivetohit"] = (325, null);
            Stat["poisoncount"] = (326, null);
            Stat["damageframerate"] = (327, null);
            Stat["pierceidx"] = (328, null);
            Stat["passivefiremastery"] = (329, null);
            Stat["passiveltngmastery"] = (330, null);
            Stat["passivecoldmastery"] = (331, null);
            Stat["passivepoismastery"] = (332, null);
            Stat["passivefirepierce"] = (333, null);
            Stat["passiveltngpierce"] = (334, null);
            Stat["passivecoldpierce"] = (335, null);
            Stat["passivepoispierce"] = (336, null);
            Stat["passivecriticalstrike"] = (337, null);
            Stat["passivedodge"] = (338, null);
            Stat["passiveavoid"] = (339, null);
            Stat["passiveevade"] = (340, null);
            Stat["passivewarmth"] = (341, null);
            Stat["passivemasterymeleeth"] = (342, null);
            Stat["passivemasterymeleedmg"] = (343, null);
            Stat["passivemasterymeleecrit"] = (344, null);
            Stat["passivemasterythrowth"] = (345, null);
            Stat["passivemasterythrowdmg"] = (346, null);
            Stat["passivemasterythrowcrit"] = (347, null);
            Stat["passiveweaponblock"] = (348, null);
            Stat["passivesummonresist"] = (349, null);
            Stat["modifierlistskill"] = (350, null);
            Stat["modifierlistlevel"] = (351, null);
            Stat["lastsenthppct"] = (352, null);
            Stat["sourceunittype"] = (353, null);
            Stat["sourceunitid"] = (354, null);
            Stat["shortparam1"] = (355, null);
            Stat["questitemdifficulty"] = (356, null);
            Stat["passivemagmastery"] = (357, null);
            Stat["passivemagpierce"] = (358, null);

            #endregion

            // To support stuff like [52]+[23]/256 >= x
            // [52,8] >= 123
            // item.getStatEx(123, 123) >= 123
            foreach (var statValue in Stat.Values.Distinct().ToList())
            {
                if (statValue.Item2 == null)
                {
                    Stat[statValue.Item1.ToString()] = (statValue.Item1, null);
                }
                else
                {
                    Stat[statValue.Item1 + "," + statValue.Item2] = statValue;
                }
            }

            InverseStat = Stat.ToLookup(o => o.Value, o => o.Key);
        }
    }
}
